export const siteConfig = {
  name: "Project Atlas",
  author: "Andrzej Delgado",
  jobTitle: "Principal Product Designer · Design Engineering Lead",
  tagline: "Product Designer × Design Engineer × Product Leader.",
  intro:
    "Hi, I'm Andrzej! As a designer with 15+ years of experience, I love crafting solutions that benefit the user and the business. I get excited about growth, designing end to end solutions, working on strategy, and leading teams to success.",
  location: "Greater Málaga Metropolitan Area, ES",
  bio: "Principal Product Designer and Design Engineering Lead.",
  // Override at deploy time with NEXT_PUBLIC_SITE_URL if needed (e.g. preview
  // deployments). Falls back to the canonical production origin.
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://delgado.vc",
  ogImage: "/og.svg",
  description:
    "Personal site of Andrzej Delgado — Principal Product Designer and Design Engineering Lead. Case studies on multi-brand design systems (Saturn Heavy), the Progressive Design Model, UI Crux, FeelsFast performance work, and the Design Engineering practice.",
  keywords: [
    "Andrzej Delgado",
    "Andrzej Delgado portfolio",
    "Principal Product Designer",
    "Design Engineering Lead",
    "design systems",
    "multi-brand design systems",
    "Saturn Heavy",
    "Progressive Design Model",
    "PDM",
    "Halo UI",
    "Tones color system",
    "Token Mapping",
    "Surface Deck Levels",
    "Composite Components",
    "Component-Level Dark Mode",
    "UI Crux",
    "FeelsFast",
    "design engineering",
    "iGaming design",
    "W3C design tokens",
    "Storybook",
    "Panda CSS",
    "APCA contrast",
    "OKLCH",
    "Next.js portfolio",
  ],
  email: "hey@andrzej.so",
  social: [
    {
      key: "github",
      label: "GitHub",
      href: "https://github.com/andrzejdelgado",
    },
    {
      key: "linkedin",
      label: "LinkedIn",
      href: "https://www.linkedin.com/in/andrzejdelgado/",
    },
    {
      key: "medium",
      label: "Medium",
      href: "https://medium.com/@andrzej.delgado",
    },
    {
      key: "adplist",
      label: "ADPList",
      href: "https://adplist.org/mentors/andrzej-delgado",
    },
    { key: "email", label: "Email", href: "mailto:hey@andrzej.so" },
  ],
} as const;
